ch3/blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'), # /
    url(r'^post/$', PostLV.as_view(), name='post_list'), # /post/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'), # /post/example/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'), # /archive/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'), # /2012/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'), # /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'), # /2012/nov/10/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'), # /today/
    url(r'^tag/$',TagTV.as_view(), name='tag_cloud'), #/tag/
    url(r'^tag/(?P<tag>[^/]+(?u))/$',PostTOL.as_view(), name='tagged_object_list'), #/tag/tagname/
    url(r'^search/$',SearchFormView.as_view(),name='search'),
]

ch3/blogproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static # 정적 파일 처리하는 뷰를 호출하도록 그에맞는 URL패턴을 반환하는 함수
from django.conf import settings # settings.py모듈에서 정의한 항목을 담은 객체를 참조하는 레퍼런스 변수

from blog.views import HomeView
from blog.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^accounts/register/$',UserCreateView.as_view(),name='register'),
    url(r'^accounts/register/done/$',UserCreateDoneTV.as_view(),name='register_done'),

    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^blog/', include('blog.urls',namespace='blog')),
    url(r'^photo/',include('photo.urls',namespace='photo')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ch3/photo/urls.py
from django.conf.urls import url
from photo.views import *

urlpatterns = [
    url(r'^$',AlbumLV.as_view(),name='index'),
    url(r'^album/$',AlbumLV.as_view(), name='album_list'),
    url(r'^album/(?P<pk>\d+)/$',AlbumDV.as_view(), name='album_detail'),
    url(r'^photo/(?P<pk>\d+)/$',PhotoDV.as_view(), name='photo_detail'),
]

ch3/blog/models.py
from __future__ import unicode_literals #파이썬2,3 문자열 처리 호환
from django.db import models
from django.core.urlresolvers import reverse #reverse 함수는 URL패턴을 만들어주는 함수
from django.utils.encoding import python_2_unicode_compatible #파이썬2,3 문자열 처리 호환
from tagging.fields import TagField # 태그라이브러리
# Create your models here.
@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE',max_length=50)
    slug = models.SlugField('SLUG',unique=True,allow_unicode=True,help_text='one word for title alias') #allow_unicode하면 한글처리가능
    description = models.CharField('DESCRIPTION',max_length=100,blank=True,help_text='simple description text')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date',auto_now_add=True)#antu_now_add = 객체가 생성될 때 자동 기록
    modify_date = models.DateTimeField('Modify_Date',auto_now=True)#auto_now = 데이터베이스에 저장될 때 자동 기록
    tag = TagField()

    class Meta: #필드 외에 필요한 파라미터는 메타클래스에 정의
        verbose_name = 'post' #테이블 단수 별칭
        verbose_name_plural = 'posts' #테이블 복수 별칭
        db_table = 'my_post' #데이터베이스에 저장되는 테이블 이름을 'my_post' 로함
        ordering = ('-modify_date',) # 모델객체 리스트 출력시 정렬을 modify_date기준 내림차순

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=(self.slug,)) # 장고 내장 함수

    def get_previous_post(self):
        return self.get_previous_by_modify_date() #장고 내장 함수

    def get_next_post(self):
        return self.get_next_by_modify_date() #장고 내장 함수

ch3/photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse
from photo.fields import ThumbnailImageField

# Create your models here.

@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description',max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('photo:album_detail',args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description',blank=True)
    upload_date = models.DateTimeField('Upload Date',auto_now_add=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail',args=(self.id,))

ch3/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word') # label = 서치폼 왼쪽에 나오는 글 , search_word는 필드에 대한 아이디로 구분하는데 씀

ch3/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from blog.models import Post
from django.views.generic.base import TemplateView
from tagging.models import Tag, TaggedItem #추가
from tagging.views import TaggedObjectList #추가

from django.views.generic.edit import FormView #폼 제네릭 뷰
from blog.forms import PostSearchForm # 검색폼으로 사용할 사용자정의 클래스임포트
from django.db.models import Q # 검색기능에 필요함
# 인증기능
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
# Create your views here.

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'

class HomeView(TemplateView):
    template_name = 'home.html'

class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'

class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'

class SearchFormView(FormView): # FormView는 get요청으로 왔을때 보여줄 폼 설정하고 폼에서 사용자입력이 완료되면 post로 가면서 유효성체크
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'
    #form_valid는 POST로 왔을 때 에러가 없으면 실행될 함수
    def form_valid(self, form):
        schWord = '%s' % self.request.POST['search_word'] # post요청에 'search_word' 파라미터를 추출, 그워드를 schWord에 저장
        post_list = Post.objects.filter(Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()
        #icontains 연산자는 대소문자를 구분않고 단어 포함되어있는지 검사
        #distinct 함수는 중복 제외 결국 서로다른 레코드객체들을 포스트리스트에 저장
        context = {} # 이제 템플릿에 보내줄 컨텍스트변수를 사전 형식으로 정의
        context['form'] = form #PostSearchForm을 컨텍스트변수 form에 지정
        context['search_term'] = schWord # 검색어도 넘김
        context['object_list'] = post_list # 검색결과도 넘김
        return render(self.request, self.template_name, context) #render함수덕분에 리다이렉트 안됨 FormView가 원래 리다이렉트함
        # render가 템플릿파일이랑 컨테스트변수를 처리해서 최총적으로 HttpResponse객체를 반환
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')
class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

ch3/photo/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from photo.models import Album,Photo
# Create your views here.

class AlbumLV(ListView):
    model = Album
class AlbumDV(DetailView):
    model = Album
class PhotoDV(DetailView):
    model = Photo

ch3/blog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Hello Programming{% endblock %}</title> <!-- 하위페이지마다 페이지 제목을 다르게 할 수 있습니다. -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/> <!--block extrastyle base.html파일에서 사용하는 base.css파일 이외에 하위페이지에서 필요한 css파일 정의 가능-->
  </head>
  <body>
    <div id="header">
      <h2 class="maintitle">Hello Programming</h2>
      {% if user.is_active %}
      <h4 class="welcome">Welcome, <strong>{%firstof user.get_short_name %}</strong> / <a href="{% url 'password_change'%}">Change Password</a> / <a href="{% url 'logout'%}">Logout</a></h4>
      {% else %}
      <h4 class="welcome">Welcome, Anonymous / <a href="{% url 'login'%}">Login</a> / <a href="{% url 'register'%}">Register</a></h4>
      {% endif %}
    </div>


    <div id="menu">
      <li><a href="{% url 'home'%}">Home</a></li>
      <li><a href="{% url 'blog:index'%}">Blog</a></li>
      <li><a href="{% url 'photo:index'%}">Photo</a></li>
      <li><a href="#">Bookmark</a></li>

      <li><a href="#">Add&bigtriangledown;</a>
      <ul>
        <li><a href="#">Bookmark</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Photo</a></li>
      </ul>
    </li>
    <li><a href="{% url 'blog:post_archive'%}">Archive</a></li>
    <li><a href="{% url 'blog:search'%}">Search</a></li>
    <li><a href="{% url 'admin:index'%}">Admin</a></li>
    </div>
    {% block content %}{% endblock %} <!--하위페이지마다 본문내용 정의 가능-->
    {% block footer %}{% endblock %} <!--하위페이지마다 꼬리말 다르게 정의 가능-->
  </body>
</html>

ch3/blog/templates/blog/post_all.html
{% extends "base.html" %}
{% block title %}post_all.html{% endblock %}
{% block content %}
  <div id="content">
    <h1>Blog List</h1>
    {% for post in posts %}
      <h2><a href='{{post.get_absolute_url}}'>{{post.title}}</a></h2> <!-- get_absolute_url URL을 구하는 함수 (?) -->
      {{post.modify_date|date:"N d, Y"}}
      <p>
        {{post.description}}
      </p>
    {% endfor %}

    <br />
    <div>
      <span>
        {% if page_obj.has_previous %}
          <a href="?page={{page_obj.previous_page_number}}">PreviousPage</a>
        {% endif %}

        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

        {% if page_obj.has_next %}
          <a href="?page={{page_obj.next_page_number}}">NextPage</a>
        {% endif %}

      </span>
    </div>
  </div>
{% endblock%}

ch3/blog/templates/blog/post_archive.html
{% extends "base.html"%}
{% block title %}post_archive.html{% endblock %}
{% block content %}
<div id="content">
    <h1>Post Archives until {% now "N d, Y" %}</h1>
    <ul>
      {% for date in date_list %}
        <li style="display:inline;">
          <a href="{% url 'blog:post_year_archive' date|date:'Y'%}">Year-{{date|date:"Y"}}</a>
        </li>
      {% endfor %}
    </ul>
    <br />
    <div>
      <ul>
        {% for post in object_list %}
          <li>
            {{post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
          </li>
        {% endfor%}
      </ul>
    </div>

</div>
{% endblock %}

ch3/blog/templates/blog/post_archive_day.html
{% extends "base.html"%}
{% block title %}post_archive_day.html{% endblock %}
{% block content %}
<div id="content">
    <h1>Post Archives for {{day|date:"N d, Y"}}</h1>
    <div>
      <ul>
        {% for post in object_list %}
          <li>
            {{post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
          </li>
        {% endfor %}
      </ul>
    </div>
</div>
{% endblock %}

ch3/blog/templates/blog/post_archive_month.html
{% extends "base.html"%}
{% block title %}post_archive_month.html{% endblock %}
{% block content %}
<div id="content">
    <h1>Post Archives for {{month|date:"N, Y"}}</h1>
    <div>
      <ul>
        {% for post in object_list %}
        <li>
          {{post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
          <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor%}
      </ul>
    </div>
</div>
{% endblock %}  

ch3/blog/templates/blog/post_archive_year.html
{% extends "base.html"%}
{% block title %}post_archive_year.html{% endblock %}
{% block content %}
<div id="content">
    <ul>
      {% for date in date_list %}
        <li style="display:inline;">
          <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b'%}">{{date|date:"F"}}</a>
        </li>
     {% endfor %}
   </ul>
   <br />

   <div>
     <ul>
       {% for post in object_list %}
       <li>
         {{post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
         <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
       </li>
       {% endfor %}
     </ul>
   </div>
 </div>
 {% endblock %}

ch3/blog/templates/blog/post_detail.html
{% extends "base.html"%}
{% block title %}post_detail.html{% endblock %}
{% block content %}
<div id="content">
    <h2> {{object.title}}</h2>

    <p class="other_posts">
      {% if object.get_previous_by_modify_date %}
        <a href="{{object.get_previous_post.get_absolute_url}}" title="View previous post">&laquo;--{{object.get_previous_post}}</a>
      {% endif%}
      {% if object.get_next_by_modify_date %}
        | <a href="{{object.get_next_post.get_absolute_url}}" title="View next post">{{object.get_next_post}}--&raquo;</a>
      {% endif%}
    </p>
    <p class="date">
      {{object.modify_date|date:"j F Y"}}
    </p>
    <br />
    <div class="body">
      {{object.content|linebreaks}} <!-- linebreaks 는 \n 인식 가능-->
    </div>
    <div>
      <b>TAGS: </b>
      {% load tagging_tags %}
      {% tags_for_object object as tags %}
      {% for tag in tags %}
      <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
      {% endfor %}
      <a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>
    </div>
    <br />
    <div>
      {% load disqus_tags %}
      {% disqus_show_comments %}
    </div>
</div>
{% endblock %}

ch3/blog/templates/blog/post_search.html
{% extends "base.html" %}
{% block title %}post_search.html{% endblock %}
{% block content %}
<div id="content">
  <form action="." method="post"> {% csrf_token %} <!--csrf공격을 방지하기 위함-->
    {{form.as_table}}
    <input type="submit" value="Submit" />
  </form>
  <br /><br />

  {% if object_list %}
  {% for post in object_list %}
  <h2><a href='{{post.get_absolute_url}}'>{{post.title}}</a></h2>
  {{post.modify_date|date:"N d ,Y"}}
  <p>
    {{post.description}}
  </p>
  {% endfor %}
  {% elif search_term %}
  <b><i>Search Word {{search_term}} Not Found </i></b>
  {% endif %}
</div>
{% endblock %}

ch3/blog/templates/home.html
    {% extends "base.html" %} <!-- html 상속 반드시 첫줄에 와야함-->
    {% block title %}home.html{% endblock %} <!--타이틀 재정의 home.html이라고 지정-->
    {% load staticfiles %} <!--static 태그를 쓰기 위해서 로딩해야 함-->
    {% block extrastyle %}{% static "css/home.css" %}{% endblock %} <!--base.css스타일시트외에 추가적으로 home.css지정-->

    {% block content %}
    <div id="content_home">
      <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.jpg'%}" style="height:256px;" /></a>
        <h4 style="margin=0;">This is Django powered web site.</h4>
      </div>
      <hr style="margin:5px 0;" />

      <h2>Select Application</h2>
      <table id="applist">
        <tr>
          <td>
            <b><i><a href="#">Bookmark</a></i></b>
          </td>
          <td>
            You can write your own post and share to others. Donex id dlit non mi porta gravide at eget metus. Fusce dapibus, tellus ac cursus commodo
          </td>
          <td class="Edit">
            <i><a href="#">Add</a></i>
          </td>
          <td class="Edit">
            <i><a href="#">Change</a></i>
          </td>
        </tr>
        <tr>
          <td>
            <b><i><a href="{% url 'blog:index' %}">Blog</a></i></b>
          </td>
          <td>
            You can write your own post and share to others. Donex id dlit non mi porta gravide at eget metus. Fusce dapibus, tellus ac cursus commodo
          </td>
          <td class="Edit">
            <i><a href="#">Add</a></i>
          </td>
          <td class="Edit">
            <i><a href="#">Change</a></i>
          </td>
        </tr>
        <tr>
          <td>
            <b><i><a href="#">Photo</a></i></b>
          </td>
          <td>
            You can write your own post and share to others. Donex id dlit non mi porta gravide at eget metus. Fusce dapibus, tellus ac cursus commodo
          </td>
          <td class="Edit">
            <i><a href="#">Add</a></i>
          </td>
          <td class="Edit">
            <i><a href="#">Change</a></i>
          </td>
        </tr>
      </table>
    </div>
    {% endblock content %}

    {% block footer %}
    <div id="footer">
      &copy; jdk 2017
    </div>
    {% endblock footer %}

ch3/blog/templates/tagging/tagging_cloud.html
{% extends "base.html" %}
{% block title %}tagging_cloud.html{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "tagging/tag.css" %}{% endblock %}

{% block content %}
<div id="content">
  <h1>Blog Tag Cloud</h1>
  <div class="tag-cloud">
    {% load tagging_tags %}
    {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
    {% for tag in tags %}
    <span class="tag-{{tag.font_size}}"><a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}} ({{tag.font_size}})</a></span>
    {% endfor %}
  </div>
</div>
{% endblock %}

ch3/blog/templates/tagging/tagging_post_list.html
{% extends "base.html" %}
{% block title %}tagging_post_list.html{% endblock %}
{% block content %}
<div id="content">
  <h1>Posts for tag - {{tag.name}}</h1>
  {% for post in object_list %}
    <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
    {{ post.modify_date|date:"N d ,Y"}}
    <p>
      {{post.description}}
    </p>
  {% endfor%}
</div>
{% endblock %}

ch3/photo/templates/photo/album_detail.html
{% extends "base.html" %}
{% block title%}album_detail.html{%endblock%}
{% load staticfiles%}
{% block extrastyle%}{% static "photo/photo.css"%}{% endblock%}
{% block content %}
<div id="content">
  <h2 style="display:inline">{{object.name}}</h2>
  &emsp;<b><i>{{object.description}}</i></b>
  <hr />
  <div class="album-detail">
    {% for photo in object.photo_set.all %} <!--object.photo_set.all은 이 앨범객체에 들어있는 모든 사진이 있는 객체로 구성된 리스트-->
      <div class="album-detail-photo">
        <a href="{{photo.get_absolute_url}}"><img class="thumbnail" src="{{photo.image.thumb_url}}" /></a>
        <li>
          {{photo.title}}
        </li>
        <li>
          {{photo.upload_date|date:"Y-m-d"}}
        </li>
      </div>
    {% endfor%}
  </div>
</div>
{% endblock%}

ch3/photo/templates/photo/album_list.html
{% extends "base.html" %}
{% block title%}album_list{% endblock%}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{%endblock%}
{% block content %}
<div id="content">
  {% for item in object_list%}
    <div class="clear_float">
      <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{item.name}}</a></h2>
      &emsp;<b><i>{{item.description}}</i></b>
    </div>
    <hr />
    <div class="album-list">
      {% for photo in item.photo_set.all|slice:":5" %}
        <div class="album-list-photo">
          <a href="{{photo.get_absolute_url}}"><img class="thumbnail" src="{{photo.image.thumb_url}}" /></a>
        </div>
      {% endfor%}
    </div>
  {% endfor%}
</div>
{% endblock%}

ch3/photo/templates/photo/photo_detail.html
{% extends "base.html" %}
{% block title%}photo_detail.html{%endblock%}
{% load staticfiles%}
{% block extrastyle%}{% static "photo/photo.css"%}{% endblock%}
{% block content %}
<div id="content">
  <h2>{{object.title}}</h2>
  <table class="photo-detail">
    <tr>
      <td>
        <a href="{{object.image.url}}"><img style="max-width:100%" src="{{object.image.url}}"/></a>
      </td>
      <td>
        <ul>
          <li>
            Photo Description
          </li>
          {% if object.description %}<p>{{object.description|linebreaks}}</p>
          {% else %}<p>(blank)</p>
          {% endif %}
          <li>
            Date Uploaded
          </li>
          <p>
            {{object.upload_date}}
          </p>
          <li>
            Album Name
          </li>
          <p>
            <a href="{% url 'photo:album_detail' object.album.id %}">{{object.album.name}}</a>
          </p>
        </ul>
      </td>
    </tr>
  </table>
</div>
{% endblock%}